# Generated by Django 4.2.7 on 2023-12-06 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='slug_field',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
