# Generated by Django 4.2.7 on 2023-12-03 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_alter_employee_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_full_time',
            field=models.BooleanField(null=True),
        ),
    ]
