# Generated by Django 4.2.7 on 2023-12-03 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_employee_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='level',
            field=models.CharField(choices=[('jr.', 'Junior'), ('sen', 'Senior'), ('reg', 'Regular')], default='Regular', max_length=25),
        ),
    ]
