# Generated by Django 4.2.7 on 2023-12-04 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_alter_employee_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='IT', max_length=50)),
                ('salary', models.PositiveIntegerField(default=1500)),
            ],
        ),
    ]
