# Generated by Django 4.2.7 on 2023-12-04 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_project_employee_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='project',
            field=models.ManyToManyField(related_name='employees', to='web.project'),
        ),
    ]
