# Generated by Django 4.2.7 on 2023-12-05 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_alter_category_parent_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='review',
            field=models.TextField(blank=True, null=True),
        ),
    ]
