# Generated by Django 4.2.7 on 2023-12-05 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0019_alter_employee_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='start_date',
        ),
    ]
